jobs:
  - job: HelloWorld
    variables:
      system.debug: true
      timeoutInMinutes: 2
    strategy:
      maxParallel: 2
      matrix:
        Linux:
          vmImage: ubuntu-latest
        Windows:
          vmImage: windows-latest
    pool:
      vmImage: $(vmImage)
    
    steps:
    - script: pwsh -Command "& '.\build.ps1'"
    
